def custom_song(name, place, adjective, noun1, noun2, noun3, noun4, noun5, noun6):
    print("\n\n")
    print(f"{place} is falling down.")
    print(f"Falling down, falling down.")
    print(f"{place} is falling down.")
    print(f"My {adjective} {name}.")
    print("\n")
    print(f"Build it up with {noun1} and {noun2}.")
    print(f"{noun1} and {noun2}, {noun1} and {noun2}.")
    print(f" Build it up with {noun1} and {noun2}.")
    print(f"My {adjective} {name}")
    print("\n")
    print(f"{noun1} and {noun2} will wash away.")
    print(f"Wash away, wash away")
    print(f"{noun1} and {noun2} will wash away.")
    print(f"My {adjective} {name}")
    print("\n")
    print(f" Build  it up with {noun3} and {noun4}.")
    print(f"{noun3} and {noun4}, {noun3} and {noun4}.")
    print(f" Build it up with {noun3} and {noun4}.")
    print(f"My {adjective} {name}")
    print("\n")
    print(f"{noun3} and {noun4} will not stay.")
    print(f"Will not stay, will not stay.")
    print(f"{noun3} and {noun4} will not stay.")
    print(f"My {adjective} {name}.")
    print("\n")
    print(f"Build it up with {noun5} and {noun6}.")
    print(f"{noun5} and {noun6}, {noun5} and {noun6}.")
    print(f"Build it up with {noun5} and {noun6}.")
    print(f"My {adjective} {name}.")
    print("\n")
    print(f"{noun5} and {noun6} will bend and bow.")
    print(f"Bend and bow, bend and bow.")
    print(f"{noun5} and {noun6} will bend and bow.")
    print(f"My {adjective} {name},")
    print("\n")
    print(f"Build it up with silver and gold.")
    print(f"Silver and gold, silver and gold.")
    print(f"Build it up with silver and gold.")
    print(f"My {adjective} {name}.")
    print("\n")
    print(f"Silver and gold will be stolen away.")
    print(f"Stolen away, stolen away.")
    print(f"Silver and gold will be stolen away.")
    print(f"My {adjective} {name}.")
    print("\n")
    print(f"Set a man to watch all night.")
    print(f"Watch all night, watch all night.")
    print(f"Set a man to watch all night.")
    print(f"My {adjective} {name}")
    print("\n")
    print(f"Suppose the man should fall asleep.")
    print(f"Fall asleep, fall asleep.")
    print(f"Suppose the man should fall asleep.")
    print(f"My {adjective} {name}.")
    print("\n")
    print(f"Give him a pipe to smoke all night.")
    print(f"Smoke all night, smoke all night.")
    print(f"Give him a pipe to smoke all night.")
    print(f"My {adjective} {name}")


name = input("Please enter a name: ")
place = input(" Please enter a location: ")
adjective = input("Give me an adjective: ")
noun1 = input("Please enter a noun: ")
noun2 = input("Give me another noun: ")
noun3 = input("Give me another noun:")
noun4 = input("Give me another noun: ")
noun5 = input("Give me another noun: ")
noun6 = input("Give me another noun: ")

custom_song(name, place, adjective, noun1, noun2, noun3, noun4, noun5, noun6)
